from flask import Flask, render_template, Response
import cv2

app = Flask(__name__)

# Initialize OpenCV's video capture (webcam by default)
camera = cv2.VideoCapture(0)

def generate_frames():
    while True:
        # Read frame from the camera
        success, frame = camera.read()
        if not success:
            break
        else:
            # Encode the frame as JPEG to send to the browser
            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            # Yield frame in byte format to stream it
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/video_feed')
def video_feed():
    # Return a response with the frames generated by OpenCV
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == "__main__":
    app.run(port=5001,debug=True)
